[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "music-generator"
version = "0.1.0"
description = "Generates music with ML using LSTM"
readme = "README.md"
requires-python = ">=3.11,<4.0"
authors = [{ name="Jan", email="uutbr@student.kit.edu" }]
license = { text="MIT" }
keywords = ["tensorflow", "music21", "matplotlib", "AI", "ML", "LSTM"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

dependencies = [
  "music21>=9.7",
  "matplotlib>=3.10",
<<<<<<< HEAD
=======
  "prompt-toolkit>=3.0"
>>>>>>> 77d4819494d4c1a549c16c3d95be71a5e2f8a8b9
]


[project.optional-dependencies]
nogpu =  ["tensorflow_cpu>=2.19"]
gpu = ["tensorflow>=2.19"]


<<<<<<< HEAD
=======
[project.scripts]
music-gen = "music_generation_lstm:main"


>>>>>>> 77d4819494d4c1a549c16c3d95be71a5e2f8a8b9
[tool.ruff]
line-length = 120
