services:
  app:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        - EDiITION=2.19.0
#       - EDITION=2.19.0-gpu
    volumes:
        - ../data/:/app/data:cached
    working_dir: /app
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
      - TF_CPP_MIN_LOG_LEVEL=2
    stdin_open: true   # -i
    tty: true
    command: music-gen
