x-default-service: &default-service
  build:
    context: ../
    dockerfile: .docker/Dockerfile
  image: music-gen:default
  volumes:
      - ../data/:/app/data:cached
  working_dir: /app
  user: "1000:1000"
  stdin_open: true
  tty: true
  command: music-gen

services:
  app:
    <<: *default-service

