services:
  app:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        - EDITION=2.19.0
#       - EDITION=2.19.0-gpu
    volumes:
        - ../data/:/app/data:cached
    working_dir: /app
    user: "1000:1000"
    stdin_open: true   # -i
    tty: true
    command: music-gen
