name: Lint with Ruff

on:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Lint with Ruff
        run: ruff . --output-format=github
